name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        target: [x64-linux]
        
    steps:
      - uses: actions/checkout@v4

      - name: Install Clang 20
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
          sudo ln -sf /usr/bin/clang-20   /usr/bin/clang
          sudo ln -sf /usr/bin/clang++-20 /usr/bin/clang++
          clang --version
          clang++ --version

      - name: Configure
        run: cmake --preset ${{ matrix.target }}

      - name: Build
        run: cmake --build --preset ${{ matrix.target }} --config Release

      - name: Test
        run: ctest --preset ${{ matrix.target }} --output-on-failure

  build-windows:
    runs-on: windows-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        target: [x64-windows-msvc]

    steps:
      - uses: actions/checkout@v4

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: cmake --preset ${{ matrix.target }}

      - name: Build
        run: cmake --build --preset ${{ matrix.target }} --config Release

      - name: Test
        run: ctest --preset ${{ matrix.target }} --output-on-failure

  build-wasm:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install Ninja
        run: sudo apt-get update && sudo apt-get install -y ninja-build

      - name: Setup Emscripten SDK
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest
          actions-cache-folder: emsdk-cache

      - name: Configure
        run: emcmake cmake --preset wasm32-emscripten
        env:
          EMSDK: ${{ env.EMSDK }}

      - name: Build
        run: cmake --build --preset wasm32-emscripten --config Release --verbose

      - name: Test
        run: ctest --preset wasm32-emscripten --output-on-failure
